# GitLab CI/CD Pipeline Configuration for PubGameNightFinder

# Limit Git history depth for faster cloning
variables:
    GIT_DEPTH: 1

# Define the pipeline stages
stages:
    - build
    - test
    - deploy

# Optional: Placeholder for a build step (e.g., JS bundling, dependency install)
build-job:
    stage: build
    image: node:18
    script:
        - echo "Build stage (e.g., npm ci, compile assets) – not used yet."
    tags:
        - docker # Remove if not needed by your runner

# ✅ Unit test job for Python backend
unit-test-job:
    stage: test
    image: python:3.9-alpine
    script:
        - python --version
        - pip install --upgrade pip
        - pip install -r backend/requirements.txt
        - export PYTHONPATH=$PYTHONPATH:/builds/sweng25_group13/sweng25_group13_pubgamenightfinder/backend
        - pytest backend/tests/ --cov=backend/ --junitxml=report.xml
    artifacts:
        reports:
            junit: report.xml
    coverage: '/^TOTAL.*\s+(\d+%)$/'
    tags:
        - docker # Remove if your runner doesn't require this
    after_script:
        - rm -rf /builds/*
        - rm -rf /tmp/*

# Optional: Linting job for frontend (React Native)
lint-test-job:
    stage: test
    image: node:18
    script:
        - echo "Linting frontend..."
        - npm ci
        - npm run lint # Assumes you have a lint script in package.json
    tags:
        - docker # Remove if not needed

# Optional: Deployment job placeholder
deploy-job:
    stage: deploy
    script:
        - echo "Deploy stage – not implemented yet."
    environment: production
    tags:
        - docker # Remove if not needed
